### ISSUE TITLE
Building Projects: [Android] Extension attached causes build fail in 2024.400 runtimes because build.gradle keys are not expanded correctly

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5173]
### Description
The attached project compiles fine in the 2024.200.0.516 runtime, but fails with 2024.400.0.548 with the following error:

```
C:\temp\GMS2CACHE\BLANK_GAME_246AA223_E7EC9E5A\android\Default\library\src\com\google\licensingservicehelper\LicensingServiceHelper.java:30: error: package com.google.api.client.json.jackson2 does not exist
import com.google.api.client.json.jackson2.JacksonFactory;
                                          ^
C:\temp\GMS2CACHE\BLANK_GAME_246AA223_E7EC9E5A\android\Default\library\src\com\google\licensingservicehelper\LicensingServiceHelper.java:31: error: package com.google.api.client.json.webtoken does not exist
import com.google.api.client.json.webtoken.JsonWebSignature;
```

We compared the differences between the runtimes but could not figure out the cause. Is it because the `google-http-client` library is updated in the 400 runtime?

### Steps To Reproduce
1. Compile the project for android VM with runtime 2024.200.0.516 and succeeds.
2. Compile with 2024.400.0.548 and see failure

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.499 Runtime v2024.200.0.516

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[634ffd18-e027-426b-a5be-50b65bd78632](https://api.gamemaker.io/api/github/downloads/634ffd18-e027-426b-a5be-50b65bd78632)

**Comment by shichen85** [comment]
https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.jackson2
https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.webtoken

The libraries mentioned in the compile error are both under the `google-http-client`: https://cloud.google.com/java/docs/reference/google-http-client/latest/overview

**Comment by DiasFranciscoA** [comment]
This was fixed with PR: https://github.com/YoYoGames/GameMaker/pull/3839

It was a problem with the asset compiler.
