### ISSUE TITLE
[HTML5] Function references in arrays cannot be called anymore

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#7949]
### Description
When having a function, either in a script or as an "object function":

function Test() { show_debug_message("hi"); }

and assigned to an array

```
var xx = [];
array_push(xx, Test);
```

If you try to call it like so:

`xx[0]();`

HTML5 throws an error:

`gmlxx[__yy_gml_array_check_index(...)] is not a function`

This does NOT happen when assigning a method to the array, then calling it.

Obviously this does work in all other platforms (tested Windows, Android, GX.games).

This used to work fine in 2024.6 and below. I know this because my UI library gooey makes use of an array of callbacks.

This happens both from latest monthly release runtime 2024.8.128 and from latest Beta runtime 2024.1100.0.658.

### Steps To Reproduce
Example project included, but basically create a function, add it to an array and then try calling it by referencing the function from the array.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[d4a575e8-42be-411f-8af3-567c4aa0c25a](https://api.gamemaker.io/api/github/downloads/d4a575e8-42be-411f-8af3-567c4aa0c25a)

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664.
