### ISSUE TITLE
Android YYC still fails to build in 2024.1400.0.970

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#14012]
### Description
Attempt to compile attached project for Android YYC in dev config.

Generated C++ code will not compile

### Steps To Reproduce
Sample output 
[arm64-v8a] Compile++      : yoyo-app0 <= gml_GlobalScript_BattleEffects.gml.cpp
[arm64-v8a] Compile++      : yoyo-app0 <= gml_GlobalScript_Bosses.gml.cpp
jni/libyoyo-app0/../../gml_GlobalScript_Bosses.gml.cpp:2453:168: error: cannot pass object of non-trivial type 'YYRValue' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
 2453 | __Args__[1] = (YYGML_CreateConstantArray( __ret3__, pSelf, 4, (YYRValue*)&g_pString884_CF63DE65, (YYRValue*)&gs_constArg0_CF63DE65, (YYRValue*)&g_pString885_CF63DE65, g_undefined ));
      |                                                                                                                                                                        ^
C:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1400.4.970/yyc/include/YYGML.h:575:21: note: expanded from macro 'g_undefined'
  575 | #define g_undefined (*((YYRValue*)&g_undefinedRV))
      |                     ^
jni/libyoyo-app0/../../gml_GlobalScript_Bosses.gml.cpp:2469:98: error: cannot pass object of non-trivial type 'YYRValue' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
 2469 | __Args__[1] = (YYGML_CreateConstantArray( __ret4__, pSelf, 2, (YYRValue*)&g_pString887_CF63DE65, g_undefined ));
      |                                                                                                  ^
C:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1400.4.970/yyc/include/YYGML.h:575:21: note: expanded from macro 'g_undefined'
  575 | #define g_undefined (*((YYRValue*)&g_undefinedRV))
      |                     ^
jni/libyoyo-app0/../../gml_GlobalScript_Bosses.gml.cpp:2485:98: error: cannot pass object of non-trivial type 'YYRValue' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
 2485 | __Args__[1] = (YYGML_CreateConstantArray( __ret5__, pSelf, 2, (YYRValue*)&g_pString889_CF63DE65, g_undefined ));
      |                                                                                                  ^
C:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1400.4.970/yyc/include/YYGML.h:575:21: note: expanded from macro 'g_undefined'
  575 | #define g_undefined (*((YYRValue*)&g_undefinedRV))
      |                     ^
jni/libyoyo-app0/../../gml_GlobalScript_Bosses.gml.cpp:2501:168: error: cannot pass object of non-trivial type 'YYRValue' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
 2501 | __Args__[1] = (YYGML_CreateConstantArray( __ret6__, pSelf, 4, (YYRValue*)&g_pString891_CF63DE65, (YYRValue*)&gs_constArg1_CF63DE65, (YYRValue*)&g_pString892_CF63DE65, g_undefined ));
      |

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1400.4.991 Runtime v2024.1400.4.970

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26200.0

### Which platform(s) are you seeing the problem on?
Android

[39446615-2909-4cbe-afd4-179d2c363228](https://api.gamemaker.io/api/github/downloads/39446615-2909-4cbe-afd4-179d2c363228)

**Comment by rwkay** [comment]
what is the GML that is causing this - can you isolate it at all?
